### ISSUE TITLE
关于光源投影矩阵的计算

### ISSUE THREAD

**Issue by lwj-cg** [weiyu666/GAMES202homework#1]
你好，请问你在生成阴影贴图的pass，光源处虚拟相机的投影矩阵是怎么设置的，让它能正好包围住模型的AABB包围盒吗？对应你代码里的什么地方呢？

**Comment by weiyu666** [comment]
你好最近有点事忙才看到~ 你说的pass是不是指的webglrender 中的 Shadow pass与Camera pass？

> 光源处虚拟相机的投影矩阵是怎么设置的是在 
class DirectionalLight的CalcLightMVP呀也在这里调用传进shader
` constructor(light, translate, scale, vertexShader, fragmentShader) {
        let lightMVP = light.CalcLightMVP(translate, scale);    //返回光源处的 MVP 矩阵绑定
 super({
            'uLightMVP': { type: 'matrix4fv', value: lightMVP }
        }, [], vertexShader, fragmentShader, light.fbo);
    }`
