### ISSUE TITLE
计算环境光贴图sh系数，for循环笔误了？

### ISSUE THREAD

**Issue by MrBean947724451** [weiyu666/GAMES202homework#2]
![image](https://user-images.githubusercontent.com/10281442/118460697-86551180-b72f-11eb-92cc-66ff1344d32a.png)
此处是 SHNum吧

**Comment by weiyu666** [comment]
sumweight 这个助教说没有用！又征询了一下另外两个大佬都说这个loop没有的；
![210603095552](https://user-images.githubusercontent.com/22174508/120574470-f367e700-c451-11eb-9b4b-bd35acdbb45a.png)
