### ISSUE TITLE
请问计算间接光那里，蒙特卡洛计算积分后不需要把结果除以sample_count吗？

### ISSUE THREAD

**Issue by Rilliane** [weiyu666/GAMES202homework#3]
我看了一下，好像代码里没有除以sample_count的部分，我也不太确定应该怎么做

**Comment by weiyu666** [comment]
需要的呀我写了的呀!你说的应该是作业4 的pbr的吧?我已经除了采样次数的sample_count;不知道你说的我是哪里写的有问题?
![image](https://user-images.githubusercontent.com/22174508/140299388-74ae95e7-e5fe-46e3-bfcf-ab47fda84153.png)

![image](https://user-images.githubusercontent.com/22174508/140299535-f171d645-2ba6-46d3-b73f-362a2c65bba9.png)
