### ISSUE TITLE
请问一下GAMES 202作业4中重要性采样时候G项的K取值问题

### ISSUE THREAD

**Issue by TheShot** [weiyu666/GAMES202homework#4]
按道理来说，E(μ)代表着的是表面一次弹射有多少能量可以离开表面，其实就是直接光照，那么k应该取值(roughness +1) * (roughness + 1) / 8。而您用的是k = (roughness * roughness) / 2，这个值我看的是算间接光照时候取这个，但是取这个值得结果确实和作业4文档中的结果很像，除了分辨率问题我好像看着一样。   因为之前文档也出过错误，所以希望和您请教一下，这地方应该取哪个k？为什么？ 谢谢啦

**Comment by weiyu666** [comment]
是因为作业4场景使用啦IBL光照的Remapping,所以才选择 k=  (roughness * roughness) / 2 ,直接光照才k= (roughness +1) * (roughness + 1) / 8 ;你可以看一下skybox我记得用了IBL啦,虽然时间有点久啦;
![)EE85 TJPJA`DHITFA`Y@7](https://user-images.githubusercontent.com/22174508/156143413-a12ffc34-9688-4e12-87d2-a3e7482d8621.jpg)
