### ISSUE TITLE
这里需要考虑光线和法线夹角大于90度的情况吗，我的理解是光线和法线的夹角越大，所需要的偏移就越大，感觉好像是取min

### ISSUE THREAD

**Issue by fxrc2018** [weiyu666/GAMES202homework#5]
https://github.com/weiyu666/GAMES202homework/blob/bb4dfec0bfc87701b9d226b9ebbc9e797f6681d4/homework1/homework1/src/shaders/phongShader/phongFragment.glsl#L136

**Comment by weiyu666** [comment]
不需要呀，还是使用的max！大于90度都黑了哪来的影？大于90 度如图是下面射上来的黑的没必要哈哈。
![bais大于90度](https://user-images.githubusercontent.com/22174508/197005993-72f0b69a-17b7-4c72-977a-521973630c84.png)

**Comment by fxrc2018** [comment]
> 不需要呀，还是使用的max！大于90度都黑了哪来的影？大于90 度如图是下面射上来的黑的没必要哈哈。 ![bais大于90度](https://user-images.githubusercontent.com/22174508/197005993-72f0b69a-17b7-4c72-977a-521973630c84.png)
1.0 - dot(normal, lightDir) ，如果是同向的话，这个值不是都小于1吗，取max不是没太大的意义吗

**Comment by weiyu666** [comment]
有意义的！你说的同向是不是指的是normal, lightDir 之间的夹角小于90°，你好好想想阴影在这个时候的表现~;首先shadow  bias使用一个0.05的偏移来解决因为阴影贴图受限于分辨率，在距离光源比较远的情况下，多个片段可能从深度贴图的同一个值中去采样。使用点乘 1.0 - dot(normal, lightDir)根据表面朝向光线的角度更改偏移量，有一个偏移量的最大值0.05，和一个最小值0.005，它们是基于表面法线和光照方向的。这样像地板这样的表面几乎与光源垂直，得到的偏移就很小，而比如立方体的侧面这种表面得到的偏移就更大。

**Comment by weiyu666** [comment]
啊我把值写错了！应该是这样的float bias = max(0.05 * (1.0 - dot(normal, lightDir)), 0.005);

**Comment by weiyu666** [comment]
已修改
