### ISSUE TITLE
作业三：mipmap

### ISSUE THREAD

**Issue by luluxiu666** [weiyu666/GAMES202homework#6]
您好，我看您作业三的代码好像没有用mipmap实现，请问有什么可以参考的文章之类的嘛

**Comment by weiyu666** [comment]
是的我确实没有使用mipmap来优化，jiafen加分项当时由于工作等事情较忙又快到交作业的时间截止期限！只能先放弃了。
![Q7LJE ZOPHDDP M_3RWWF21](https://github.com/weiyu666/GAMES202homework/assets/22174508/6ccd9a80-392e-4ad3-b769-0e6489412195)
对于文章资料什么的看一看一下以下的两篇：
1、  [Games202 Hw3 Screen Space Ray Tracing](https://howl144.github.io/2023/06/10/00017.%20Games202%20Hw3/)
2、  [实现Mipmap优化的 Screen Space Ray Tracing（Hiz优化）](https://www.drflower.top/posts/8cc56e6d/#Bonus-1%EF%BC%9A%E5%AE%9E%E7%8E%B0Mipmap%E4%BC%98%E5%8C%96%E7%9A%84-Screen-Space-Ray-Tracing%EF%BC%88Hiz%E4%BC%98%E5%8C%96%EF%BC%89)

**Comment by luluxiu666** [comment]
好的，谢谢您的回复

**Comment by weiyu666** [comment]
没事互相学习哈哈哈，代码有什么不对的地方欢迎指出~
